version: '3.8'

services:
  backend:
    build: ./backend
    container_name: polybot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/polybot
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=supersecretkeychangeinproduction
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: polybot_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://82.165.175.160:8000
    depends_on:
      - backend
    command: npm run dev -- --host

  db:
    image: postgres:15-alpine
    container_name: polybot_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polybot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: polybot_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
